export const LOADING = 'PACKAGES/LOADING';
export const LOAD_PACKAGES_DONE = 'PACKAGES/LOAD_PACKAGES_DONE';
export const ADD_PACKAGE = 'PACKAGES/ADD_PACKAGE';
export const ADD_PACKAGES = 'PACKAGES/ADD_PACKAGES';
export const REMOVE_PACKAGE = 'PACKAGES/REMOVE_PACKAGE';
export const SET_TRANSACTION_CODE = 'PACKAGES/SET_TRANSACTION_CODE';
export const SET_PERIODS = 'PACKAGES/SET_PERIODS';
export const CHANGE_SUCCESS = 'PACKAGES/CHANGE_SUCCESS';
